-- Task graph for unified-model-catalog.
-- Ingest into the session SQL store with the `sql` tool.
--
-- Schema: todos(id, title, description, status) + todo_deps(todo_id, depends_on).
-- Allowed status values: 'pending', 'in_progress', 'done', 'blocked'.

INSERT INTO todos (id, title, description, status) VALUES
  ('umc-enum-extension',
   'Add PostProcessor variant to ModelCategory',
   'Extend the ModelCategory enum in src-tauri/src/managers/model/mod.rs:29-34 with a PostProcessor variant. Update any exhaustive match sites (expected to be only the few locations currently matching on Transcription vs System). Verifier: AC-001-a (cargo test model_category_has_post_processor_variant). See tasks/umc-enum-extension/context.md.',
   'pending'),
  ('umc-metadata-blocks',
   'Introduce TranscriptionMetadata and LlmMetadata on ModelInfo',
   'Add optional nested transcription_metadata and llm_metadata fields to ModelInfo with #[serde(default)] on Option<T>. Leave the existing flat fields in place for one release for backward compat. Add cargo tests for populated-metadata invariants and legacy-JSON roundtrip. Verifiers: AC-003-a, AC-003-b. See tasks/umc-metadata-blocks/context.md.',
   'pending'),
  ('umc-catalog-migration',
   'Migrate GGUF entries from managers/llm/catalog.rs to unified catalog',
   'Translate every LlmCatalogEntry in src-tauri/src/managers/llm/catalog.rs into a ModelInfo with category = PostProcessor and the LLM-specific fields under llm_metadata. Target file managers/model/catalog.rs; if projected size exceeds 650 lines, split into managers/model/catalog/{mod,transcription,post_processor}.rs. Add an entry-count cargo test. Verifier: AC-002-a. See tasks/umc-catalog-migration/context.md.',
   'pending'),
  ('umc-download-unify',
   'Route all downloads through managers/model/download.rs',
   'Extend managers/model/download.rs to pick the on-disk target directory by category (<app-data>/models/ for Transcription, <app-data>/llm/ for PostProcessor). Rewire managers/llm/mod.rs + inference.rs to use the unified pipeline. Add a cargo test that downloads a fixture post-processor entry and validates the sha256 hash. Verifiers: AC-004-a, AC-004-b. See tasks/umc-download-unify/context.md.',
   'pending'),
  ('umc-event-unify',
   'Unify ModelDownloadProgress event shape with category field',
   'Collapse the two ModelDownloadProgress struct definitions into one in managers/model/mod.rs with { id, category, downloaded_bytes, total_bytes, status }. Regenerate bindings.ts. Ensure single-struct-definition audit passes. Verifier: AC-005-a. See tasks/umc-event-unify/context.md.',
   'pending'),
  ('umc-command-unify',
   'Consolidate Tauri command surface with category arg + deprecation shims',
   'Introduce download_model(id, category), get_models(category?), delete_model(id). Reduce download_llm_model, get_llm_models, delete_llm_model to thin forwarders with warn!-level deprecation log. Add a cargo test for the shim forward + deprecation log. Regenerate bindings.ts. Verifiers: AC-006-a, AC-006-b. See tasks/umc-command-unify/context.md.',
   'pending'),
  ('umc-delete-llm-catalog',
   'Delete managers/llm/catalog.rs and managers/llm/download.rs',
   'Remove src-tauri/src/managers/llm/catalog.rs and src-tauri/src/managers/llm/download.rs once all callers are rewired. Update managers/llm/mod.rs to drop the module declarations. Verifier: AC-002-b (script audit). See tasks/umc-delete-llm-catalog/context.md.',
   'pending'),
  ('umc-models-page-ui',
   'Add category filter + per-card badge to ModelsSettings.tsx',
   'Add a segmented control (All | Transcription | Post-processing) above the list and per-card badge pills. Use i18n keys; no raw enum tokens. Respect existing color tokens (rest #EEEEEE, accent orange). Verifiers: AC-007-a, AC-007-b, AC-007-c. See tasks/umc-models-page-ui/context.md.',
   'pending'),
  ('umc-post-process-embed',
   'Embed unified Models picker in PostProcessingSettings',
   'Replace src/components/settings/post-processing/local-models/LlmModelCatalog.tsx with a filter-locked embed of the unified ModelsSettings component (or delete it entirely and render the unified component inline). Add a Manage models deep-link. Verifier: AC-008-a, AC-008-b. See tasks/umc-post-process-embed/context.md.',
   'pending'),
  ('umc-settings-migration',
   'Migrate AppSettings.post_process_local_model_id on load',
   'Add a settings migration helper in src-tauri/src/settings.rs that maps any legacy post_process_local_model_id to the corresponding unified catalog id. Idempotent. Cargo test with a fixture settings JSON. Verifier: AC-009-a. See tasks/umc-settings-migration/context.md.',
   'pending'),
  ('umc-i18n-sweep',
   'Add filter / badge / deep-link keys to all 20 locales',
   'Add settings.models.filter.*, settings.models.badge.*, settings.postProcessing.manageModelsLink keys to src/i18n/locales/en/translation.json with English copy, then mirror them into the 19 other locale files with the English string as a placeholder per the i18n-pruning skill. Verifier: AC-010-a (bun run scripts/check-translations.ts). See tasks/umc-i18n-sweep/context.md.',
   'pending'),
  ('umc-dep-hygiene',
   'Run dep-hygiene skill on the diff',
   'After managers/llm/catalog.rs + download.rs are deleted, invoke the dep-hygiene skill (cargo machete / knip / depcheck) and remove any now-orphaned crates or npm packages. Verifier: AC-011-a. See tasks/umc-dep-hygiene/context.md.',
   'pending'),
  ('umc-file-size-check',
   'Confirm 800-line file-size cap is respected',
   'Run bun run scripts/check-file-sizes.ts. If managers/model/catalog.rs exceeds the cap, split into submodules under managers/model/catalog/. Verifier: AC-012-a. See tasks/umc-file-size-check/context.md.',
   'pending'),
  ('umc-qc-backend',
   'QC: backend build + test green',
   'Run cd src-tauri; cargo test --lib and cd src-tauri; cargo clippy. Confirm zero errors and no new clippy warnings on touched crates. Verifier: AC-001-b. See tasks/umc-qc-backend/context.md.',
   'pending'),
  ('umc-qc-live-app',
   'QC: live-app verification per AGENTS.md',
   'Drive the numbered click-through steps in coverage.json for AC-005-b, AC-007-a, AC-007-b, AC-007-c, AC-008-b, and AC-013-a using .\\scripts\\launch-toaster-monitored.ps1. Record evidence in journal.md. Verifier: AC-013-a. See tasks/umc-qc-live-app/context.md.',
   'pending'),
  ('umc-feature-qc',
   'QC: run coverage + tasks gates',
   'Run pwsh scripts/check-feature-coverage.ps1 -Feature unified-model-catalog and pwsh scripts/check-feature-tasks.ps1 -Feature unified-model-catalog; confirm both exit 0. Hand off to superpowers:executing-plans.',
   'pending');

INSERT INTO todo_deps (todo_id, depends_on) VALUES
  ('umc-metadata-blocks', 'umc-enum-extension'),
  ('umc-catalog-migration', 'umc-metadata-blocks'),
  ('umc-download-unify', 'umc-catalog-migration'),
  ('umc-event-unify', 'umc-download-unify'),
  ('umc-command-unify', 'umc-event-unify'),
  ('umc-delete-llm-catalog', 'umc-command-unify'),
  ('umc-models-page-ui', 'umc-command-unify'),
  ('umc-post-process-embed', 'umc-models-page-ui'),
  ('umc-settings-migration', 'umc-catalog-migration'),
  ('umc-i18n-sweep', 'umc-models-page-ui'),
  ('umc-i18n-sweep', 'umc-post-process-embed'),
  ('umc-dep-hygiene', 'umc-delete-llm-catalog'),
  ('umc-file-size-check', 'umc-catalog-migration'),
  ('umc-qc-backend', 'umc-delete-llm-catalog'),
  ('umc-qc-backend', 'umc-settings-migration'),
  ('umc-qc-live-app', 'umc-post-process-embed'),
  ('umc-qc-live-app', 'umc-settings-migration'),
  ('umc-qc-live-app', 'umc-i18n-sweep'),
  ('umc-feature-qc', 'umc-qc-backend'),
  ('umc-feature-qc', 'umc-qc-live-app'),
  ('umc-feature-qc', 'umc-dep-hygiene'),
  ('umc-feature-qc', 'umc-file-size-check');
